# vim:fileencoding=utf-8:ft=conf:foldmethod=marker

# Font {{{

map ctrl+minus          change_font_size all -2.0
map ctrl+plus           change_font_size all +2.0

# }}}

# Scroll {{{

map ctrl+shift+k scroll_line_up
map ctrl+shift+j scroll_line_down

# }}}

# Tab management {{{

map kitty_mod+right next_tab
map kitty_mod+left  previous_tab
map kitty_mod+t     new_tab_with_cwd
map kitty_mod+q     close_tab
map kitty_mod+.     move_tab_forward
map kitty_mod+,     move_tab_backward
map kitty_mod+alt+t set_tab_title

# }}}

# Clipboard {{{

map shift+ctrl+c  copy_to_clipboard
map shift+ctrl+v  paste_from_clipboard

map ctrl+x>ctrl+c  copy_to_clipboard
map ctrl+x>ctrl+v  paste_from_clipboard

map ctrl+shift+v  paste_from_clipboard

# }}}

# Mac {{{

map cmd+t   new_tab_with_cwd

# }}}

# Mouse {{{

mouse_map left click ungrabbed mouse_select_tab

# }}}
