# vim:fileencoding=utf-8:ft=conf:foldmethod=marker

# Hints {{{

map ctrl+q>h>h kitten hints --type hash --program @
map ctrl+q>h>l kitten hints --type line --program @
map ctrl+q>h>u kitten hints --type url --program @
map ctrl+q>h>w kitten hints --type word --program @

map ctrl+q>shift+h>h kitten hints --type hash --program -
map ctrl+q>shift+h>l kitten hints --type line --program -
map ctrl+q>shift+h>u kitten hints --type url --program -
map ctrl+q>shift+h>w kitten hints --type word --program -

# }}}

# Tab management {{{

map ctrl+q>p        previous_tab
map ctrl+q>n        next_tab
map ctrl+q>c        new_tab_with_cwd
map ctrl+q>x        close_tab
map ctrl+q>,        set_tab_title

map ctrl+q>1 goto_tab 1
map ctrl+q>2 goto_tab 2
map ctrl+q>3 goto_tab 3
map ctrl+q>4 goto_tab 4
map ctrl+q>5 goto_tab 5
map ctrl+q>6 goto_tab 6
map ctrl+q>7 goto_tab 7
map ctrl+q>8 goto_tab 8
map ctrl+q>9 goto_tab 9
map ctrl+q>0 goto_tab 10

# }}}

# Layout management {{{

# https://sw.kovidgoyal.net/kitty/layouts.html?highlight=mirro#id3

enabled_layouts vertical,grid,fat:full_size=1;bias=50,horizontal,tall,splits,stack

map ctrl+q>l>l next_layout

map ctrl+q>l>f goto_layout fat:full_size=1;bias=50
map ctrl+q>l>g goto_layout grid
map ctrl+q>l>h goto_layout horizontal
map ctrl+q>l>p goto_layout splits
map ctrl+q>l>s goto_layout stack
map ctrl+q>l>t goto_layout tall
map ctrl+q>l>v goto_layout vertical

# }}}

# Marker {{{

map ctrl+q>m>c            create_marker
map ctrl+q>m>r            remove_marker
map ctrl+q>m>p            scroll_to_mark prev
map ctrl+q>m>n            scroll_to_mark next

# }}}

# Misc {{{

map ctrl+q>semicolon      kitty_shell overlay
map ctrl+q>ctrl+t>ctrl+t  clear_terminal reset active
map ctrl+q>s              show_scrollback
map ctrl+q>k              new_os_window_with_cwd

# }}}

# Window management {{{

map ctrl+q>q    close_window

map ctrl+q>w>w  new_window_with_cwd
map ctrl+q>w>c  new_window_with_cwd

map ctrl+q>w>s  start_resizing_window

map ctrl+q>w>p previous_window
map ctrl+q>w>n next_window

map ctrl+q>w>1 first_window
map ctrl+q>w>2 second_window
map ctrl+q>w>3 third_window
map ctrl+q>w>4 fourth_window
map ctrl+q>w>5 fifth_window
map ctrl+q>w>6 sixth_window
map ctrl+q>w>7 seventh_window
map ctrl+q>w>8 eighth_window
map ctrl+q>w>9 ninth_window
map ctrl+q>w>0 tenth_window

# }}}
