version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "{{_input_:stack_name}}"
s3_prefix = "{{_input_:stack_name}}"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []

