[ignore]
directories = [
  "*.egg-info",
  ".IdeaIC11",
  ".IdeaIC12",
  ".IdeaIC13",
  ".activator",
  ".aws-sam",
  ".build",
  ".bundle",
  ".cabal-sandbox",
  ".cache",
  ".class",
  ".coverage",
  ".dart_tool",
  ".eggs",
  ".env",
  ".git",
  ".hypothesis",
  ".idea",
  ".mypy_cache",
  ".next",
  ".parcel-cache",
  ".pytest_cache",
  ".ruff_cache",
  ".sass-cache",
  ".stack-work",
  ".terraform",
  ".terragrunt-cache",
  ".tmpBin",
  ".tox",
  ".vagrant",
  ".venv",
  "__pycache__",
  "_darcs",
  "android",
  "bower_components",
  "build",
  "dist",
  "elm-stuff",
  "ios",
  "maven_repository",
  "node_modules",
  "storybook-static",
  "target",
  "vendor",
]
extensions = [
  "bak",
  "bin",
  "class",
  "dll",
  "dylib",
  "dyn_c",
  "dyn_hi",
  "exe",
  "fasl",
  "hi",
  "jar",
  "jpeg",
  "jpg",
  "lib",
  "lock",
  "log",
  "o",
  "obj",
  "pdb",
  "png",
  "pyc",
  "retry",
  "so",
  "swp",
  "temp",
  "tmp",
]
files = [
  "*.bak",
  "*.bundle.*",
  "*.chunk.*",
  "*.crt",
  "*.csr",
  "*.db",
  "*.dmp",
  "*.key",
  "*.lock",
  "*.log",
  "*.map",
  "*.min.css",
  "*.min.js",
  "*.orig",
  "*.p12",
  "*.pem",
  "*.pfx",
  "*.pid",
  "*.rej",
  "*.sqlite",
  "*.swo",
  "*.swp",
  "*.temp",
  "*.tmp",
  "*~",
  ".DS_Store",
  ".aider.*",
  ".env.*",
  "Cargo.lock",
  "Pipfile.lock",
  "Thumbs.db",
  "core.*",
  "desktop.ini",
  "package-lock.json",
  "pnpm-lock.yaml",
  "poetry.lock",
  "requirements*.txt",
  "vgcore.*",
  "yarn.lock",
]
