  GlueDatabase:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-database.html
    Type: AWS::Glue::Database
    Properties:
      # DatabaseInput:
      #   # LocationUri: # String
      #   # CreateTableDefaultPermissions:
      #   # - # Permissions:
      #   #     # - # String
      #   # # Principal:
      #   #     # # DataLakePrincipalIdentifier: # String
      #   # Description: # String
      #   # Parameters: # Json
      #   # TargetDatabase:
      #   # # DatabaseName: # String
      #   # # CatalogId: # String
      #   # Name: # String
      CatalogId: # String
