  SSMMaintenanceWindow:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-maintenancewindow.html
    Type: AWS::SSM::MaintenanceWindow
    Properties:
      # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-maintenancewindow.html
      # StartDate: # String
      # Description: # String
      AllowUnassociatedTargets: # Boolean
      Cutoff: # Integer
      Schedule: # String
      Duration: # Integer
      # ScheduleOffset: # Integer
      # EndDate: # String
      # Tags:
      #   - Key: # String
      #     Value: # String
      Name: # String
      # ScheduleTimezone: # String
