  EC2RouteTable:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-routetable.html
    Type: AWS::EC2::RouteTable
    Properties:
      # Tags:
      #   - Key: # String
      #     Value: # String
      VpcId: # String
    # !GetAtt THIS.RouteTableId (String)
