  WAFRegionalXssMatchSet:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-wafregional-xssmatchset.html
    Type: AWS::WAFRegional::XssMatchSet
    Properties:
      # XssMatchTuples:
      #   - TextTransformation: # String
      #     # FieldToMatch:
      #     # Type: # String
      #     # # Data: # String
      Name: # String
