  GuardDutyIPSet:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-guardduty-ipset.html
    Type: AWS::GuardDuty::IPSet
    Properties:
      # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-guardduty-ipset.html
      Format: # String
      Activate: # Boolean
      DetectorId: # String
      # Tags:
      #   - Key: # String
      #     Value: # String
      # Name: # String
      Location: # String
