  SecretsManagerSecret:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-secretsmanager-secret.html
    Type: AWS::SecretsManager::Secret
    Properties:
      # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-secretsmanager-secret.html
      # Description: # String
      # KmsKeyId: # String
      # SecretString: # String
      # GenerateSecretString:
      #   # ExcludeUppercase: # Boolean
      #   # RequireEachIncludedType: # Boolean
      #   # IncludeSpace: # Boolean
      #   # ExcludeCharacters: # String
      #   # GenerateStringKey: # String
      #   # PasswordLength: # Integer
      #   # ExcludePunctuation: # Boolean
      #   # ExcludeLowercase: # Boolean
      #   # SecretStringTemplate: # String
      #   # ExcludeNumbers: # Boolean
      # ReplicaRegions:
      #   - # KmsKeyId: # String
      #     Region: # String
      # Tags:
      #   - Key: # String
      #     Value: # String
      # Name: # String
