  IoTWirelessDeviceProfile:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iotwireless-deviceprofile.html
    Type: AWS::IoTWireless::DeviceProfile
    Properties:
      # Name: # String
      # LoRaWAN:
      #   # SupportsClassB: # Boolean
      #   # ClassBTimeout: # Integer
      #   # PingSlotPeriod: # Integer
      #   # PingSlotDr: # Integer
      #   # PingSlotFreq: # Integer
      #   # SupportsClassC: # Boolean
      #   # ClassCTimeout: # Integer
      #   # MacVersion: # String
      #   # RegParamsRevision: # String
      #   # RxDelay1: # Integer
      #   # RxDrOffset1: # Integer
      #   # RxFreq2: # Integer
      #   # RxDataRate2: # Integer
      #   # FactoryPresetFreqsList:
      #   # - # Integer
      #   # MaxEirp: # Integer
      #   # MaxDutyCycle: # Integer
      #   # SupportsJoin: # Boolean
      #   # RfRegion: # String
      #   # Supports32BitFCnt: # Boolean
      # Tags:
      #   - Key: # String
      #     Value: # String
    # !GetAtt THIS.Arn (String)
    # !GetAtt THIS.Id (String)
