  EC2TransitGatewayMulticastGroupSource:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-transitgatewaymulticastgroupsource.html
    Type: AWS::EC2::TransitGatewayMulticastGroupSource
    Properties:
      GroupIpAddress: # String
      TransitGatewayMulticastDomainId: # String
      NetworkInterfaceId: # String
    # !GetAtt THIS.TransitGatewayAttachmentId (String)
    # !GetAtt THIS.SubnetId (String)
    # !GetAtt THIS.ResourceId (String)
    # !GetAtt THIS.ResourceType (String)
    # !GetAtt THIS.GroupMember (Boolean)
    # !GetAtt THIS.GroupSource (Boolean)
    # !GetAtt THIS.MemberType (String)
    # !GetAtt THIS.SourceType (String)
