  MSKBatchScramSecret:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-msk-batchscramsecret.html
    Type: AWS::MSK::BatchScramSecret
    Properties:
      ClusterArn: # String
      # SecretArnList:
      #   - # String
