  DMSReplicationSubnetGroup:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-replicationsubnetgroup.html
    Type: AWS::DMS::ReplicationSubnetGroup
    Properties:
      # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-replicationsubnetgroup.html
      ReplicationSubnetGroupDescription: # String
      # ReplicationSubnetGroupIdentifier: # String
      SubnetIds:
        - # String
      # Tags:
      #   - Key: # String
      #     Value: # String
