  RedshiftClusterSubnetGroup:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-redshift-clustersubnetgroup.html
    Type: AWS::Redshift::ClusterSubnetGroup
    Properties:
      Description: # String
      SubnetIds:
        - # String
      # Tags:
      #   - Key: # String
      #     Value: # String
    # !GetAtt THIS.ClusterSubnetGroupName (String)
