  CodeDeployDeploymentGroup:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codedeploy-deploymentgroup.html
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codedeploy-deploymentgroup.html
      # AlarmConfiguration:
      #   # Alarms:
      #   # - # Name: # String
      #   # Enabled: # Boolean
      #   # IgnorePollAlarmFailure: # Boolean
      ApplicationName: # String
      # AutoRollbackConfiguration:
      #   # Enabled: # Boolean
      #   # Events:
      #   # - # String
      # AutoScalingGroups:
      #   - # String
      # BlueGreenDeploymentConfiguration:
      #   # DeploymentReadyOption:
      #   # # ActionOnTimeout: # String
      #   # # WaitTimeInMinutes: # Integer
      #   # GreenFleetProvisioningOption:
      #   # # Action: # String
      #   # TerminateBlueInstancesOnDeploymentSuccess:
      #   # # Action: # String
      #   # # TerminationWaitTimeInMinutes: # Integer
      # Deployment:
      #   # Description: # String
      #   # IgnoreApplicationStopFailures: # Boolean
      #   # Revision:
      #   # # GitHubLocation:
      #   #   # CommitId: # String
      #   #   # Repository: # String
      #   # # RevisionType: # String
      #   # # S3Location:
      #   #   # Bucket: # String
      #   #   # # BundleType: # String
      #   #   # # ETag: # String
      #   #   # Key: # String
      #   #   # # Version: # String
      # DeploymentConfigName: # String
      # DeploymentGroupName: # String
      # DeploymentStyle:
      #   # DeploymentOption: # String
      #   # DeploymentType: # String
      # ECSServices:
      #   - ClusterName: # String
      #     ServiceName: # String
      # Ec2TagFilters:
      #   - # Key: # String
      #     # Type: # String
      #     # Value: # String
      # Ec2TagSet:
      #   # Ec2TagSetList:
      #   # - # Ec2TagGroup:
      #   #     # - # Key: # String
      #   #     # # Type: # String
      #   #     # # Value: # String
      # LoadBalancerInfo:
      #   # ElbInfoList:
      #   # - # Name: # String
      #   # TargetGroupInfoList:
      #   # - # Name: # String
      #   # TargetGroupPairInfoList:
      #   # - # ProdTrafficRoute:
      #   #     # # ListenerArns:
      #   #     #   # - # String
      #   # # TargetGroups:
      #   #     # - # Name: # String
      #   # # TestTrafficRoute:
      #   #     # # ListenerArns:
      #   #     #   # - # String
      # OnPremisesInstanceTagFilters:
      #   - # Key: # String
      #     # Type: # String
      #     # Value: # String
      # OnPremisesTagSet:
      #   # OnPremisesTagSetList:
      #   # - # OnPremisesTagGroup:
      #   #     # - # Key: # String
      #   #     # # Type: # String
      #   #     # # Value: # String
      # OutdatedInstancesStrategy: # String
      ServiceRoleArn: # String
      # Tags:
      #   - Key: # String
      #     Value: # String
      # TriggerConfigurations:
      #   - # TriggerEvents:
      #     # - # String
      #     # TriggerName: # String
      #     # TriggerTargetArn: # String
