  CassandraTable:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cassandra-table.html
    Type: AWS::Cassandra::Table
    Properties:
      # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cassandra-table.html
      KeyspaceName: # String
      # TableName: # String
      # RegularColumns:
      #   - ColumnName: # String
      #     ColumnType: # String
      PartitionKeyColumns:
        - ColumnName: # String
          ColumnType: # String
      # ClusteringKeyColumns:
      #   - # Column:
      #     # ColumnName: # String
      #     # ColumnType: # String
      #     # OrderBy: # String
      # BillingMode:
      #   Mode: # String
      #   # ProvisionedThroughput:
      #   # ReadCapacityUnits: # Integer
      #   # WriteCapacityUnits: # Integer
      # PointInTimeRecoveryEnabled: # Boolean
      # Tags:
      #   - Key: # String
      #     Value: # String
      # DefaultTimeToLive: # Integer
      # EncryptionSpecification:
      #   EncryptionType: # String
      #   # KmsKeyIdentifier: # String
