  NimbleStudioLaunchProfile:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-nimblestudio-launchprofile.html
    Type: AWS::NimbleStudio::LaunchProfile
    Properties:
      # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-nimblestudio-launchprofile.html
      # Description: # String
      Ec2SubnetIds:
        - # String
      LaunchProfileProtocolVersions:
        - # String
      Name: # String
      # StreamConfiguration:
      #   ClipboardMode: # String
      #   Ec2InstanceTypes:
      #     - # String
      #   # MaxSessionLengthInMinutes: # Double
      #   StreamingImageIds:
      #     - # String
      #   # MaxStoppedSessionLengthInMinutes: # Double
      #   # SessionStorage:
      #   # # Root:
      #   #   # # Linux: # String
      #   #   # # Windows: # String
      #   # Mode:
      #   # - # String
      StudioComponentIds:
        - # String
      StudioId: # String
      # Tags:
      #   ANY_KEY: # String
    # !GetAtt THIS.LaunchProfileId (String)
