  DirectoryServiceSimpleAD:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-directoryservice-simplead.html
    Type: AWS::DirectoryService::SimpleAD
    Properties:
      # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-directoryservice-simplead.html
      # CreateAlias: # Boolean
      # Description: # String
      # EnableSso: # Boolean
      Name: # String
      Password: # String
      # ShortName: # String
      Size: # String
      # VpcSettings:
      #   SubnetIds:
      #     - # String
      #   VpcId: # String
    # !GetAtt THIS.Alias (String)
    # !GetAtt THIS.DnsIpAddresses (List)
