  LogsLogStream:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-logstream.html
    Type: AWS::Logs::LogStream
    Properties:
      LogGroupName: # String
      # LogStreamName: # String
