  ConnectCampaignsCampaign:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-connectcampaigns-campaign.html
    Type: AWS::ConnectCampaigns::Campaign
    Properties:
      # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-connectcampaigns-campaign.html
      ConnectInstanceArn: # String
      # DialerConfig:
      #   # ProgressiveDialerConfig:
      #   # BandwidthAllocation: # Double
      #   # PredictiveDialerConfig:
      #   # BandwidthAllocation: # Double
      Name: # String
      # OutboundCallConfig:
      #   ConnectContactFlowArn: # String
      #   # ConnectSourcePhoneNumber: # String
      #   ConnectQueueArn: # String
      # Tags:
      #   - Key: # String
      #     Value: # String
    # !GetAtt THIS.Arn (String)
