  SecretsManagerRotationSchedule:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-secretsmanager-rotationschedule.html
    Type: AWS::SecretsManager::RotationSchedule
    Properties:
      # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-secretsmanager-rotationschedule.html
      SecretId: # String
      # HostedRotationLambda:
      #   RotationType: # String
      #   # RotationLambdaName: # String
      #   # KmsKeyArn: # String
      #   # MasterSecretArn: # String
      #   # VpcSecurityGroupIds: # String
      #   # ExcludeCharacters: # String
      #   # MasterSecretKmsKeyArn: # String
      #   # SuperuserSecretArn: # String
      #   # SuperuserSecretKmsKeyArn: # String
      #   # VpcSubnetIds: # String
      # RotationLambdaARN: # String
      # RotationRules:
      #   # ScheduleExpression: # String
      #   # Duration: # String
      #   # AutomaticallyAfterDays: # Integer
      # RotateImmediatelyOnUpdate: # Boolean
