  DMSEventSubscription:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-eventsubscription.html
    Type: AWS::DMS::EventSubscription
    Properties:
      # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-eventsubscription.html
      # SourceType: # String
      # EventCategories:
      #   - # String
      # Enabled: # Boolean
      # SubscriptionName: # String
      SnsTopicArn: # String
      # SourceIds:
      #   - # String
      # Tags:
      #   - Key: # String
      #     Value: # String
