  EC2TransitGatewayVpcAttachment:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-transitgatewayvpcattachment.html
    Type: AWS::EC2::TransitGatewayVpcAttachment
    Properties:
      # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-transitgatewayvpcattachment.html
      TransitGatewayId: # String
      VpcId: # String
      SubnetIds:
        - # String
      # AddSubnetIds:
      #   - # String
      # RemoveSubnetIds:
      #   - # String
      # Tags:
      #   - Key: # String
      #     Value: # String
      # Options: # Json
    # !GetAtt THIS.Id (String)
