  WAFRegionalIPSet:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-wafregional-ipset.html
    Type: AWS::WAFRegional::IPSet
    Properties:
      # IPSetDescriptors:
      #   - Type: # String
      #     Value: # String
      Name: # String
