  BatchJobQueue:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-batch-jobqueue.html
    Type: AWS::Batch::JobQueue
    Properties:
      # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-batch-jobqueue.html
      # JobQueueName: # String
      ComputeEnvironmentOrder:
        - ComputeEnvironment: # String
          Order: # Integer
      Priority: # Integer
      # State: # String
      # SchedulingPolicyArn: # String
      # Tags:
      #   ANY_KEY: # String
    # !GetAtt THIS.JobQueueArn (String)
