  DMSReplicationTask:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-replicationtask.html
    Type: AWS::DMS::ReplicationTask
    Properties:
      # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-replicationtask.html
      # ReplicationTaskSettings: # String
      # CdcStartPosition: # String
      # CdcStopPosition: # String
      MigrationType: # String
      TargetEndpointArn: # String
      ReplicationInstanceArn: # String
      # TaskData: # String
      # CdcStartTime: # Double
      # ResourceIdentifier: # String
      TableMappings: # String
      # ReplicationTaskIdentifier: # String
      SourceEndpointArn: # String
      # Tags:
      #   - Key: # String
      #     Value: # String
