  GlobalAcceleratorAccelerator:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-globalaccelerator-accelerator.html
    Type: AWS::GlobalAccelerator::Accelerator
    Properties:
      # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-globalaccelerator-accelerator.html
      Name: # String
      # IpAddressType: # String
      # IpAddresses:
      #   - # String
      # Enabled: # Boolean
      # Tags:
      #   - Key: # String
      #     Value: # String
    # !GetAtt THIS.DnsName (String)
    # !GetAtt THIS.Ipv4Addresses (List)
    # !GetAtt THIS.Ipv6Addresses (List)
    # !GetAtt THIS.DualStackDnsName (String)
    # !GetAtt THIS.AcceleratorArn (String)
