  NetworkManagerSiteToSiteVpnAttachment:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-networkmanager-sitetositevpnattachment.html
    Type: AWS::NetworkManager::SiteToSiteVpnAttachment
    Properties:
      # CoreNetworkId: # String
      # Tags:
      #   - Key: # String
      #     Value: # String
      # VpnConnectionArn: # String
    # !GetAtt THIS.CoreNetworkArn (String)
    # !GetAtt THIS.AttachmentId (String)
    # !GetAtt THIS.OwnerAccountId (String)
    # !GetAtt THIS.AttachmentType (String)
    # !GetAtt THIS.State (String)
    # !GetAtt THIS.EdgeLocation (String)
    # !GetAtt THIS.ResourceArn (String)
    # !GetAtt THIS.AttachmentPolicyRuleNumber (Integer)
    # !GetAtt THIS.SegmentName (String)
    # !GetAtt THIS.CreatedAt (String)
    # !GetAtt THIS.UpdatedAt (String)
