  EC2VPCDHCPOptionsAssociation:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcdhcpoptionsassociation.html
    Type: AWS::EC2::VPCDHCPOptionsAssociation
    Properties:
      DhcpOptionsId: # String
      VpcId: # String
    # !GetAtt THIS.Id (String)
