  SageMakerDataQualityJobDefinition:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-dataqualityjobdefinition.html
    Type: AWS::SageMaker::DataQualityJobDefinition
    Properties:
      # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-dataqualityjobdefinition.html
      # JobDefinitionName: # String
      # DataQualityBaselineConfig:
      #   # BaseliningJobName: # String
      #   # ConstraintsResource:
      #   # # S3Uri: # String
      #   # StatisticsResource:
      #   # # S3Uri: # String
      # DataQualityAppSpecification:
      #   # ContainerArguments:
      #   # - # String
      #   # ContainerEntrypoint:
      #   # - # String
      #   ImageUri: # String
      #   # PostAnalyticsProcessorSourceUri: # String
      #   # RecordPreprocessorSourceUri: # String
      #   # Environment:
      #   # ANY_KEY: # String
      # DataQualityJobInput:
      #   # EndpointInput:
      #   # EndpointName: # String
      #   # LocalPath: # String
      #   # # S3DataDistributionType: # String
      #   # # S3InputMode: # String
      #   # BatchTransformInput:
      #   # DataCapturedDestinationS3Uri: # String
      #   # # DatasetFormat:
      #   #   # # Csv:
      #   #   #   # # Header: # Boolean
      #   #   # # Json:
      #   #   #   # # Line: # Boolean
      #   #   # # Parquet: # Boolean
      #   # LocalPath: # String
      #   # # S3DataDistributionType: # String
      #   # # S3InputMode: # String
      # DataQualityJobOutputConfig:
      #   # KmsKeyId: # String
      #   MonitoringOutputs:
      #     - # S3Output:
      #       # LocalPath: # String
      #       # # S3UploadMode: # String
      #       # S3Uri: # String
      # JobResources:
      #   # ClusterConfig:
      #   # InstanceCount: # Integer
      #   # InstanceType: # String
      #   # # VolumeKmsKeyId: # String
      #   # VolumeSizeInGB: # Integer
      # NetworkConfig:
      #   # EnableInterContainerTrafficEncryption: # Boolean
      #   # EnableNetworkIsolation: # Boolean
      #   # VpcConfig:
      #   # SecurityGroupIds:
      #   # - # String
      #   # Subnets:
      #   # - # String
      # EndpointName: # String
      RoleArn: # String
      # StoppingCondition:
      #   MaxRuntimeInSeconds: # Integer
      # Tags:
      #   - Key: # String
      #     Value: # String
    # !GetAtt THIS.JobDefinitionArn (String)
    # !GetAtt THIS.CreationTime (String)
