  NeptuneDBInstance:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-neptune-dbinstance.html
    Type: AWS::Neptune::DBInstance
    Properties:
      # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-neptune-dbinstance.html
      # DBParameterGroupName: # String
      DBInstanceClass: # String
      # AllowMajorVersionUpgrade: # Boolean
      # DBClusterIdentifier: # String
      # AvailabilityZone: # String
      # PreferredMaintenanceWindow: # String
      # AutoMinorVersionUpgrade: # Boolean
      # DBSubnetGroupName: # String
      # DBInstanceIdentifier: # String
      # DBSnapshotIdentifier: # String
      # Tags:
      #   - Key: # String
      #     Value: # String
    # !GetAtt THIS.Endpoint (String)
    # !GetAtt THIS.Port (String)
