  EC2NetworkInterfacePermission:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-networkinterfacepermission.html
    Type: AWS::EC2::NetworkInterfacePermission
    Properties:
      AwsAccountId: # String
      NetworkInterfaceId: # String
      Permission: # String
