  PinpointAPNSSandboxChannel:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-pinpoint-apnssandboxchannel.html
    Type: AWS::Pinpoint::APNSSandboxChannel
    Properties:
      # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-pinpoint-apnssandboxchannel.html
      # BundleId: # String
      # PrivateKey: # String
      # Enabled: # Boolean
      # DefaultAuthenticationMethod: # String
      # TokenKey: # String
      ApplicationId: # String
      # TeamId: # String
      # Certificate: # String
      # TokenKeyId: # String
