  PinpointEmailIdentity:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-pinpointemail-identity.html
    Type: AWS::PinpointEmail::Identity
    Properties:
      # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-pinpointemail-identity.html
      # FeedbackForwardingEnabled: # Boolean
      # DkimSigningEnabled: # Boolean
      # Tags:
      #   - # Value: # String
      #     # Key: # String
      Name: # String
      # MailFromAttributes:
      #   # MailFromDomain: # String
      #   # BehaviorOnMxFailure: # String
    # !GetAtt THIS.IdentityDNSRecordName3 (String)
    # !GetAtt THIS.IdentityDNSRecordName1 (String)
    # !GetAtt THIS.IdentityDNSRecordName2 (String)
    # !GetAtt THIS.IdentityDNSRecordValue3 (String)
    # !GetAtt THIS.IdentityDNSRecordValue2 (String)
    # !GetAtt THIS.IdentityDNSRecordValue1 (String)
