  FunctionIAMRole:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html
    Type: AWS::IAM::Role
    Properties:
      # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service:
                - lambda.amazonaws.com
                - edgelambda.amazonaws.com
      # Description: # String
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      # MaxSessionDuration: # Integer
      # Path: # String
      # PermissionsBoundary: # String
      Policies:
        - PolicyName: John Doe
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: VisualEditor0
                Effect: Allow
                Action:
                  - s3:GetObject
                Resource: '*'
      # RoleName: # String
      # Tags:
      #   - Key: # String
      #     Value: # String
    # !GetAtt THIS.Arn (String)
    # !GetAtt THIS.RoleId (String)
