  ConfigConfigurationRecorder:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-config-configurationrecorder.html
    Type: AWS::Config::ConfigurationRecorder
    Properties:
      # Name: # String
      # RecordingGroup:
      #   # AllSupported: # Boolean
      #   # IncludeGlobalResourceTypes: # Boolean
      #   # ResourceTypes:
      #   # - # String
      RoleARN: # String
