  ApiGatewayRestApi:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-restapi.html
    Type: AWS::ApiGateway::RestApi
    Properties:
      # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-restapi.html
      # ApiKeySourceType: # String
      # BinaryMediaTypes:
      #   - # String
      # Body: # Json
      # BodyS3Location:
      #   # Bucket: # String
      #   # ETag: # String
      #   # Key: # String
      #   # Version: # String
      # CloneFrom: # String
      # Description: # String
      # DisableExecuteApiEndpoint: # Boolean
      # EndpointConfiguration:
      #   # Types:
      #   # - # String
      #   # VpcEndpointIds:
      #   # - # String
      # FailOnWarnings: # Boolean
      # MinimumCompressionSize: # Integer
      # Mode: # String
      # Name: # String
      # Parameters:
      #   ANY_KEY: # String
      # Policy: # Json
      # Tags:
      #   - Key: # String
      #     Value: # String
    # !GetAtt THIS.RootResourceId (String)
