  RedshiftEndpointAuthorization:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-redshift-endpointauthorization.html
    Type: AWS::Redshift::EndpointAuthorization
    Properties:
      # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-redshift-endpointauthorization.html
      ClusterIdentifier: # String
      Account: # String
      # VpcIds:
      #   - # String
      # Force: # Boolean
    # !GetAtt THIS.Grantor (String)
    # !GetAtt THIS.Grantee (String)
    # !GetAtt THIS.AuthorizeTime (String)
    # !GetAtt THIS.ClusterStatus (String)
    # !GetAtt THIS.Status (String)
    # !GetAtt THIS.AllowedAllVPCs (Boolean)
    # !GetAtt THIS.AllowedVPCs (List)
    # !GetAtt THIS.EndpointCount (Integer)
