  IAMAccessKey:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iam-accesskey.html
    Type: AWS::IAM::AccessKey
    Properties:
      # Serial: # Integer
      # Status: # String
      UserName: # String
    # !GetAtt THIS.SecretAccessKey (String)
