  MediaPackageOriginEndpoint:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mediapackage-originendpoint.html
    Type: AWS::MediaPackage::OriginEndpoint
    Properties:
      # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mediapackage-originendpoint.html
      Id: # String
      ChannelId: # String
      # Description: # String
      # Whitelist:
      #   - # String
      # StartoverWindowSeconds: # Integer
      # TimeDelaySeconds: # Integer
      # ManifestName: # String
      # Origination: # String
      # Authorization:
      #   SecretsRoleArn: # String
      #   CdnIdentifierSecret: # String
      # HlsPackage:
      #   # SegmentDurationSeconds: # Integer
      #   # PlaylistWindowSeconds: # Integer
      #   # PlaylistType: # String
      #   # AdMarkers: # String
      #   # AdTriggers:
      #   # - # String
      #   # AdsOnDeliveryRestrictions: # String
      #   # ProgramDateTimeIntervalSeconds: # Integer
      #   # IncludeIframeOnlyStream: # Boolean
      #   # UseAudioRenditionGroup: # Boolean
      #   # IncludeDvbSubtitles: # Boolean
      #   # Encryption:
      #   # # EncryptionMethod: # String
      #   # # ConstantInitializationVector: # String
      #   # # KeyRotationIntervalSeconds: # Integer
      #   # # RepeatExtXKey: # Boolean
      #   # # SpekeKeyProvider:
      #   #   # ResourceId: # String
      #   #   # SystemIds:
      #   #   # - # String
      #   #   # Url: # String
      #   #   # RoleArn: # String
      #   #   # # CertificateArn: # String
      #   #   # # EncryptionContractConfiguration:
      #   #   #   # PresetSpeke20Audio: # String
      #   #   #   # PresetSpeke20Video: # String
      #   # StreamSelection:
      #   # # MinVideoBitsPerSecond: # Integer
      #   # # MaxVideoBitsPerSecond: # Integer
      #   # # StreamOrder: # String
      # DashPackage:
      #   # SegmentDurationSeconds: # Integer
      #   # ManifestWindowSeconds: # Integer
      #   # Profile: # String
      #   # MinUpdatePeriodSeconds: # Integer
      #   # MinBufferTimeSeconds: # Integer
      #   # SuggestedPresentationDelaySeconds: # Integer
      #   # PeriodTriggers:
      #   # - # String
      #   # IncludeIframeOnlyStream: # Boolean
      #   # ManifestLayout: # String
      #   # SegmentTemplateFormat: # String
      #   # AdTriggers:
      #   # - # String
      #   # AdsOnDeliveryRestrictions: # String
      #   # Encryption:
      #   # # KeyRotationIntervalSeconds: # Integer
      #   # # SpekeKeyProvider:
      #   #   # ResourceId: # String
      #   #   # SystemIds:
      #   #   # - # String
      #   #   # Url: # String
      #   #   # RoleArn: # String
      #   #   # # CertificateArn: # String
      #   #   # # EncryptionContractConfiguration:
      #   #   #   # PresetSpeke20Audio: # String
      #   #   #   # PresetSpeke20Video: # String
      #   # StreamSelection:
      #   # # MinVideoBitsPerSecond: # Integer
      #   # # MaxVideoBitsPerSecond: # Integer
      #   # # StreamOrder: # String
      #   # UtcTiming: # String
      #   # UtcTimingUri: # String
      # MssPackage:
      #   # ManifestWindowSeconds: # Integer
      #   # SegmentDurationSeconds: # Integer
      #   # Encryption:
      #   # # SpekeKeyProvider:
      #   #   # ResourceId: # String
      #   #   # SystemIds:
      #   #   # - # String
      #   #   # Url: # String
      #   #   # RoleArn: # String
      #   #   # # CertificateArn: # String
      #   #   # # EncryptionContractConfiguration:
      #   #   #   # PresetSpeke20Audio: # String
      #   #   #   # PresetSpeke20Video: # String
      #   # StreamSelection:
      #   # # MinVideoBitsPerSecond: # Integer
      #   # # MaxVideoBitsPerSecond: # Integer
      #   # # StreamOrder: # String
      # CmafPackage:
      #   # SegmentDurationSeconds: # Integer
      #   # SegmentPrefix: # String
      #   # Encryption:
      #   # # KeyRotationIntervalSeconds: # Integer
      #   # # SpekeKeyProvider:
      #   #   # ResourceId: # String
      #   #   # SystemIds:
      #   #   # - # String
      #   #   # Url: # String
      #   #   # RoleArn: # String
      #   #   # # CertificateArn: # String
      #   #   # # EncryptionContractConfiguration:
      #   #   #   # PresetSpeke20Audio: # String
      #   #   #   # PresetSpeke20Video: # String
      #   # # ConstantInitializationVector: # String
      #   # # EncryptionMethod: # String
      #   # StreamSelection:
      #   # # MinVideoBitsPerSecond: # Integer
      #   # # MaxVideoBitsPerSecond: # Integer
      #   # # StreamOrder: # String
      #   # HlsManifests:
      #   # - Id: # String
      #   # # ManifestName: # String
      #   # # Url: # String
      #   # # PlaylistWindowSeconds: # Integer
      #   # # PlaylistType: # String
      #   # # AdMarkers: # String
      #   # # ProgramDateTimeIntervalSeconds: # Integer
      #   # # IncludeIframeOnlyStream: # Boolean
      #   # # AdTriggers:
      #   #     # - # String
      #   # # AdsOnDeliveryRestrictions: # String
      # Tags:
      #   - Key: # String
      #     Value: # String
    # !GetAtt THIS.Arn (String)
    # !GetAtt THIS.Url (String)
