  EC2VPNGateway:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpngateway.html
    Type: AWS::EC2::VPNGateway
    Properties:
      # AmazonSideAsn: # Integer
      # Tags:
      #   - Key: # String
      #     Value: # String
      Type: # String
    # !GetAtt THIS.VPNGatewayId (String)
