  Route53ResolverResolverConfig:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-route53resolver-resolverconfig.html
    Type: AWS::Route53Resolver::ResolverConfig
    Properties:
      ResourceId: # String
      AutodefinedReverseFlag: # String
    # !GetAtt THIS.Id (String)
    # !GetAtt THIS.OwnerId (String)
    # !GetAtt THIS.AutodefinedReverse (String)
