  KendraFaq:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kendra-faq.html
    Type: AWS::Kendra::Faq
    Properties:
      # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kendra-faq.html
      IndexId: # String
      Name: # String
      # Description: # String
      # FileFormat: # String
      # S3Path:
      #   Bucket: # String
      #   Key: # String
      RoleArn: # String
      # Tags:
      #   - Key: # String
      #     Value: # String
    # !GetAtt THIS.Id (String)
    # !GetAtt THIS.Arn (String)
