  ApiGatewayDocumentationPart:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-documentationpart.html
    Type: AWS::ApiGateway::DocumentationPart
    Properties:
      # Location:
      #   # Method: # String
      #   # Name: # String
      #   # Path: # String
      #   # StatusCode: # String
      #   # Type: # String
      Properties: # String
      RestApiId: # String
    # !GetAtt THIS.DocumentationPartId (String)
