  WAFRegionalRegexPatternSet:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-wafregional-regexpatternset.html
    Type: AWS::WAFRegional::RegexPatternSet
    Properties:
      RegexPatternStrings:
        - # String
      Name: # String
