  ApiGatewayDocumentationVersion:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-documentationversion.html
    Type: AWS::ApiGateway::DocumentationVersion
    Properties:
      # Description: # String
      DocumentationVersion: # String
      RestApiId: # String
