  KMSKey:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kms-key.html
    Type: AWS::KMS::Key
    Properties:
      # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kms-key.html
      # Description: # String
      # Enabled: # Boolean
      # EnableKeyRotation: # Boolean
      KeyPolicy: # Json
      # KeyUsage: # String
      # KeySpec: # String
      # MultiRegion: # Boolean
      # PendingWindowInDays: # Integer
      # Tags:
      #   - Key: # String
      #     Value: # String
    # !GetAtt THIS.Arn (String)
    # !GetAtt THIS.KeyId (String)
