  LambdaPermission:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-permission.html
    Type: AWS::Lambda::Permission
    Properties:
      # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-permission.html
      Action: 'lambda:InvokeFunction'
      # EventSourceToken: # String
      FunctionName: !GetAtt FIXME.Arn
      Principal: s3.amazonaws.com
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !Sub 'arn:aws:s3:::FIXME'
