  NetworkManagerDevice:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-networkmanager-device.html
    Type: AWS::NetworkManager::Device
    Properties:
      # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-networkmanager-device.html
      # Description: # String
      # Tags:
      #   - Key: # String
      #     Value: # String
      GlobalNetworkId: # String
      # Location:
      #   # Address: # String
      #   # Latitude: # String
      #   # Longitude: # String
      # Model: # String
      # SerialNumber: # String
      # SiteId: # String
      # Type: # String
      # Vendor: # String
    # !GetAtt THIS.DeviceArn (String)
    # !GetAtt THIS.DeviceId (String)
