  EC2VPCEndpointServicePermissions:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpointservicepermissions.html
    Type: AWS::EC2::VPCEndpointServicePermissions
    Properties:
      # AllowedPrincipals:
      #   - # String
      ServiceId: # String
