  CodeArtifactRepository:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codeartifact-repository.html
    Type: AWS::CodeArtifact::Repository
    Properties:
      # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codeartifact-repository.html
      RepositoryName: # String
      DomainName: # String
      # DomainOwner: # String
      # Description: # String
      # ExternalConnections:
      #   - # String
      # Upstreams:
      #   - # String
      # PermissionsPolicyDocument: # Json
      # Tags:
      #   - Key: # String
      #     Value: # String
    # !GetAtt THIS.Name (String)
    # !GetAtt THIS.DomainName (String)
    # !GetAtt THIS.DomainOwner (String)
    # !GetAtt THIS.Arn (String)
