  Route53ResolverFirewallDomainList:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-route53resolver-firewalldomainlist.html
    Type: AWS::Route53Resolver::FirewallDomainList
    Properties:
      # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-route53resolver-firewalldomainlist.html
      # Name: # String
      # Domains:
      #   - # String
      # DomainFileUrl: # String
      # Tags:
      #   - Key: # String
      #     Value: # String
    # !GetAtt THIS.Id (String)
    # !GetAtt THIS.Arn (String)
    # !GetAtt THIS.DomainCount (Integer)
    # !GetAtt THIS.Status (String)
    # !GetAtt THIS.StatusMessage (String)
    # !GetAtt THIS.ManagedOwnerName (String)
    # !GetAtt THIS.CreatorRequestId (String)
    # !GetAtt THIS.CreationTime (String)
    # !GetAtt THIS.ModificationTime (String)
