  HealthLakeFHIRDatastore:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-healthlake-fhirdatastore.html
    Type: AWS::HealthLake::FHIRDatastore
    Properties:
      # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-healthlake-fhirdatastore.html
      # DatastoreName: # String
      DatastoreTypeVersion: # String
      # PreloadDataConfig:
      #   PreloadDataType: # String
      # SseConfiguration:
      #   # KmsEncryptionConfig:
      #   # CmkType: # String
      #   # # KmsKeyId: # String
      # Tags:
      #   - Key: # String
      #     Value: # String
    # !GetAtt THIS.DatastoreArn (String)
    # !GetAtt THIS.DatastoreEndpoint (String)
    # !GetAtt THIS.DatastoreId (String)
    # !GetAtt THIS.DatastoreStatus (String)
