  GameLiftScript:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-gamelift-script.html
    Type: AWS::GameLift::Script
    Properties:
      # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-gamelift-script.html
      # Version: # String
      # StorageLocation:
      #   # ObjectVersion: # String
      #   Bucket: # String
      #   Key: # String
      #   RoleArn: # String
      # Tags:
      #   - Key: # String
      #     Value: # String
      # Name: # String
    # !GetAtt THIS.Id (String)
    # !GetAtt THIS.Arn (String)
