  DataSyncLocationS3:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-datasync-locations3.html
    Type: AWS::DataSync::LocationS3
    Properties:
      # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-datasync-locations3.html
      # S3Config:
      #   BucketAccessRoleArn: # String
      S3BucketArn: # String
      # Subdirectory: # String
      # S3StorageClass: # String
      # Tags:
      #   - Key: # String
      #     Value: # String
    # !GetAtt THIS.LocationArn (String)
    # !GetAtt THIS.LocationUri (String)
