  FooFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: event.lambda_handler
      Runtime: python3.9
      CodeUri: src
      Role: !GetAtt FooFunctionRole.Arn

  FooFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunctionUrl'
      FunctionName: !GetAtt FooFunction.Arn
      Principal: '*'
      FunctionUrlAuthType: NONE

  FooFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: lambda.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  FooFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      TargetFunctionArn: !GetAtt FooFunction.Arn


Outputs:
  FooFunctionUrl:
    Value: !GetAtt FooFunctionUrl.FunctionUrl
