  DataBrewRecipe:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-databrew-recipe.html
    Type: AWS::DataBrew::Recipe
    Properties:
      # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-databrew-recipe.html
      # Description: # String
      Name: # String
      Steps:
        - # Action:
          #   Operation: # String
          #   # Parameters: # Json
          # ConditionExpressions:
          #   - Condition: # String
          #     # Value: # String
          #     TargetColumn: # String
      # Tags:
      #   - Key: # String
      #     Value: # String
