  OpsWorksUserProfile:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-opsworks-userprofile.html
    Type: AWS::OpsWorks::UserProfile
    Properties:
      # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-opsworks-userprofile.html
      # AllowSelfManagement: # Boolean
      IamUserArn: # String
      # SshPublicKey: # String
      # SshUsername: # String
    # !GetAtt THIS.SshUsername (String)
