  ServiceCatalogAppRegistryApplication:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-servicecatalogappregistry-application.html
    Type: AWS::ServiceCatalogAppRegistry::Application
    Properties:
      Name: # String
      # Description: # String
      # Tags:
      #   ANY_KEY: # String
    # !GetAtt THIS.Id (String)
    # !GetAtt THIS.Arn (String)
