  ElasticLoadBalancingV2TargetGroup:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-targetgroup.html
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-targetgroup.html
      # HealthCheckEnabled: # Boolean
      # HealthCheckIntervalSeconds: # Integer
      # HealthCheckPath: # String
      # HealthCheckPort: # String
      # HealthCheckProtocol: # String
      # HealthCheckTimeoutSeconds: # Integer
      # HealthyThresholdCount: # Integer
      # IpAddressType: # String
      # Matcher:
      #   # GrpcCode: # String
      #   # HttpCode: # String
      # Name: # String
      # Port: # Integer
      # Protocol: # String
      # ProtocolVersion: # String
      # Tags:
      #   - Key: # String
      #     Value: # String
      # TargetGroupAttributes:
      #   - # Key: # String
      #     # Value: # String
      # TargetType: # String
      # Targets:
      #   - # AvailabilityZone: # String
      #     Id: # String
      #     # Port: # Integer
      # UnhealthyThresholdCount: # Integer
      # VpcId: # String
    # !GetAtt THIS.LoadBalancerArns (List)
    # !GetAtt THIS.TargetGroupFullName (String)
    # !GetAtt THIS.TargetGroupName (String)
