  ServiceDiscoveryPrivateDnsNamespace:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-servicediscovery-privatednsnamespace.html
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
    Properties:
      # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-servicediscovery-privatednsnamespace.html
      # Description: # String
      Vpc: # String
      # Properties:
      #   # DnsProperties:
      #   # # SOA:
      #   #   # # TTL: # Double
      # Tags:
      #   - Key: # String
      #     Value: # String
      Name: # String
    # !GetAtt THIS.HostedZoneId (String)
    # !GetAtt THIS.Id (String)
    # !GetAtt THIS.Arn (String)
