worker_processes  1;

events {
  worker_connections  1024;
}


http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;

  log_format ltsv
    'time:$time_iso8601\t'
    'host:$host\t'
    'request_method:$request_method\t'
    'request_uri:$request_uri\t'
    'uri:$uri\t'
    'query_string:$query_string\t'
    'status:$status\t'
    'forwarded_for:$http_x_forwarded_for\t'
    'request_time:$request_time\t'
    # 'upstream_addr:$upstream_addr\t'
    'upstream_response_time:$upstream_response_time';
  access_log  /var/log/nginx/access.log  ltsv;

  sendfile        on;
  #tcp_nopush     on;
  keepalive_timeout  60;
  gzip  on;

  server {
    listen       8888;
    server_name  localhost;

    location / {
      proxy_pass http://localhost:3002/;
    }

    # Proxy to HTTPS
    location /res/ {
      proxy_ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
      proxy_ssl_server_name on;
      proxy_ssl_name exmaple.com;     # FIXME
      proxy_pass https://exmaple.com; # FIXME
    }
  }
}
